### ISSUE TITLE
请问能更新YOLOV8-OBB的代码吗？

### ISSUE THREAD

**Issue by yvanwy** [HorizonRDK/model_zoo#4]
ultralytics的V8.2版本中增加了obb目标检测，请问啥时候能跟进呢？

**Comment by WuChao-2024** [comment]
你好，目前正在将ultralytics的视觉方案适配X3，X5，会包括目标检测(Detect，OBB-Detect，Track-Detect)，分割（实例分割
Instance Segmentation），关键点检测（Pose），预计在9月开发者大会前释放，敬请期待。
